### ISSUE TITLE
Intermittent 500 errors

### ISSUE THREAD

**Issue by bennofs** [bennofs/nix-index#11]
Sometimes, when building the index, cloudfront returns a `500 Internal Server Error`.

This is usually goes away after some time, but it appears that these errors originate from S3 and cloudfront caches them. Changing any of the headers that affect the cache key makes the error go away (in particular, it appears that cloudflare caches two versions: one if `gzip` is included in `Accept-Encoding` and one if it isn't)

**Comment by 0xABAB** [comment]
> hmm, what was the problem with 0xABAB? I mean, it looks like most of his review comments were pretty bad / useless / wrong, but it doesn't look to me as if he did it on purpose

@bennofs Have you read more than 50% of my comments? No? Then why do you open your retarded mouth?

**Comment by bennofs** [comment]
Appears to be fixed with https://groups.google.com/d/msg/nix-devel/i7mE3ExoKuA/uypZV5oNAwAJ
