### ISSUE TITLE
Timeout for requests

### ISSUE THREAD

**Issue by bennofs** [bennofs/nix-index#12]
Nix-index should not wait forever for a request to finish, there should be a reasonable timeout. Sometimes a request is just stuck so it is better to retry rather than waiting for it to finish.

**Comment by 0xABAB** [comment]
> hmm, what was the problem with 0xABAB? I mean, it looks like most of his review comments were pretty bad / useless / wrong, but it doesn't look to me as if he did it on purpose

@bennofs Have you read more than 50% of my comments? No? Then why do you open your retarded mouth?
