### ISSUE TITLE
Verified command doesn't work anymore

### ISSUE THREAD

**Issue by 0xABAB** [bennofs/nix-index#13]
Cool tool, if it would work.

```
nix-index -f https://nixos.org/channels/nixpkgs-unstable/nixexprs.tar.xz
+ querying available packages
error: querying available packages failed
caused by: nix-env failed with error: nix-env failed with exit code 1:
error: attribute ‘webkitgtk24x’ missing, at /nix/store/i03irvxqbppszy9d439b3wvf0qla3s8q-nixexprs.tar.xz/pkgs/development/haskell-modules/hackage-packages.nix:202342:10
(use ‘--show-trace’ to show detailed location information)
```

**Comment by bennofs** [comment]
try the following:

```
$ nix-index -f 'https://github.com/NixOS/nixpkgs/archive/ce8802729430c21dd4b437f8441f278a869e4a44.tar.gz'
```

**Comment by matthewbauer** [comment]
This is a problem with nixpkgs eval: Nixos/nixpkgs#26125 and Nixos/nixpkgs#27288

**Comment by bennofs** [comment]
Yes. The command I posted above should instruct `nix-index` to use the last nixpkgs-unstable channel that doesn't have that commit.

**Comment by 0xABAB** [comment]
bennofs wrote:
> hmm, what was the problem with 0xABAB? I mean, it looks like most of his review comments were pretty bad / useless / wrong, but it doesn't look to me as if he did it on purpose

@bennofs Have you read more than 50% of my review comments? No? Then why the fuck do you open your retarded mouth? 

Please go fuck yourself.

**Comment by 0xABAB** [comment]
> hmm, what was the problem with 0xABAB? I mean, it looks like most of his review comments were pretty bad / useless / wrong, but it doesn't look to me as if he did it on purpose

@bennofs Have you read more than 50% of my comments? No? Then why do you open your retarded mouth?

**Comment by 0xABAB** [comment]
Do

**Comment by 0xABAB** [comment]
You

**Comment by bennofs** [comment]
Please, keep the discussion on topic. If you have anything to discuss with me personally, do it somewhere else (you can find me on IRC as bennofs on #freenode).
