### ISSUE TITLE
public nix-locate server instance for thin clients

### ISSUE THREAD

**Issue by milahu** [bennofs/nix-index#174]
running `nix-index` is slow and seems wasteful ...
who wants to run a public nix-locate server? : D
something like https://packages.debian.org/en/#search_contents

or, to distribute the load / obfuscate the attack surface:
make a distributed database with orbitdb over ipfs?

or, cache the 40 MByte `~/.cache/nix-index/files` file on `cache.nixos.org`
which is much faster to download than "a million small files" (compare: git object compression)

sample server: https://github.com/milahu/nix-locate-server/blob/master/nix-locate-server.go

```
curl "http://localhost:8080/bin/nix-locate%20--regex%20hello-world"
```

**Comment by Artturin** [comment]
https://github.com/Mic92/nix-index-database

**Comment by bennofs** [comment]
Public databases are available via the nix-index-database repo linked above, and a online version is already requested here #194, so closing this as solved/duplicate.
