### ISSUE TITLE
The '.out' file extension

### ISSUE THREAD

**Issue by phpcitizen** [bennofs/nix-index#197]
This is just a question, I am new to NixOS, and couldn't find an answer anywhere else.

Why there is an '.out' extension of the applications?

**Comment by KAction** [comment]
You mean this?
```
>> nix-locate '/bin/edir'
edir.out                                            348 x /nix/store/ncgjrkizci1q0fiv6f7cwrbn842341hm-edir-2.7.3/bin/edir
```

`out` is name of output. If derivation has no explicit `outputs = ...`, it has only one output named `out`. Outputs are equivalent of binary packages for dpkgs, if that helps.

**Comment by bennofs** [comment]
The answer @KAction gave is correct, the default output is called '.out' but there are also packages which have '.dev' etc. for development headers.

**Comment by phpcitizen** [comment]
Thanks guys.
