### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by lexleogryfon** [bennofs/nix-index#20]
nix-env -i nix-index, fails, after 30 min of rust compilation with out of stack error.
see https://pastebin.ca/3965443

------------------------------------------
stderr:
------------------------------------------
thread 'main' panicked at 'assertion failed: `(left == right)` (left: `Some(11)`, right: `Some(6)`)', /tmp/nix-build-rustc-1.17.0.drv-0/rustc-1.17.0-src/src/test/run-pass/out-of-stack.rs:50

exit code 101

**Comment by bennofs** [comment]
Sorry, but I think this is unrelated to nix-index. In your build, the rust compiler itself failed to build, which is not specific to nix-index as it affects all rust programs in nixpkgs. 

I might have time to look into the nixpkgs issue tomorrow though.

**Comment by bennofs** [comment]
@lexleogryfon on what channel version are you? nix-index is in the binary cache for the lastest nixpkgs master, so you shouldn't need to do any building yourself...

**Comment by bennofs** [comment]
The following command should fetch `nix-index` from the binary cache:

```
nix-env -f https://d3g5gsiof5omrk.cloudfront.net/nixpkgs/nixpkgs-18.03pre126020.931a0b8be80/nixexprs.tar.xz -iA nix-index
```

(It will use the version from nixpkgs-unstable at the time of writing this)

**Comment by lexleogryfon** [comment]
issue is fixed.
the root cause was the fact that `rutsc` was unable to compile(even at hydra). 
the `nix-channel --update` as root pulled correct fixes, and later I was able to install prebuilt binary with
`nix-env -iAb nix-index`

so case https://github.com/bennofs/nix-index/issues/20 is solved.

I'm currently writing python application around nix-locate, and run it inside nix's `pkgs.buildFHSUserEnv` . nix-locate works fine for me at this moment, and I expect further compatibility in further releases.

There are however few minor things:
1) nix-index compiling from source during my pkgs.buildFHSUserEnv, rustc compilation takes really LOOONG, I wish knew the way to force installation from prebuild binary. in nix file. I don't know, does buildFHSUserEnv support that? 
2) inside FHS, nix-index fails with message:
`error: querying available packages failed
caused by: IO error: No such file or directory (os error 2)
`
however, it is okay , so far nix-locate works for me with already existing database. at least nix-index inside FHS doesn't try to recreate it \ corrupt it.
however you may want to detect such use cases, even if they are not typical, and write more informative error message, because from message above it is not clear what file and path where it should exist.

I also wish to know where your software get a list of output files for each package\hydra_buildjob? Please explain. Just tried to look at nano output for example https://hydra.nixos.org/build/67751330#tabs-details  but don't see list of produced binaries, *.so files, man pages.

another question how to get `proper package name` output from nix-locate? for example i query for 
libXcomposite.so.1 , nix-locate outputs `xlibs.libXcomposite.out` , then I apply regex or some other string filtering function to output and get xlibs.libXcomposite . But i can't feed this to nix-env -iA. if we look at https://nixos.org/nixos/packages.html#libxcomp , we'll see xorg.libXcomposite instead of xlibs... , and that true for some other packages. I guess the only way I could get package name to install (that i can use in .nix file and nix-env), is apply regex or other string manipulation to get `.wordbetweendots. before out`, am I correct?

**Comment by bennofs** [comment]
@lexleogryfon nice to know you got it working!

As for your first question, I don't know if there is a nix option to only use prebuilt packages. 
For the second question, you're right, I need to display a better error message in this case (the error handling in general could be improved, I'll open an issue about that). I think the reason you get that error is that nix-index tries to call nix-env which is not available in the sandbox.

The file list is retrieved from the nixos cache, there are `hash.ls` (or `hash.ls.xz`) files for each thing build by hydra. See https://cache.nixos.org/52qhyxfx2xn0mlbr5rajrimaszdd6pm5.ls for your example (note: this is brotli-compressed, as  indicated by the`Content-Encoding: br` header).

The attribute name should always work for `nix-env -iA`, as the attribute names are generated from `nix-env --query --all --xml` (and some other options I forgot right now, see `src/nixpkgs.rs` for the full list of options).  `nix-build <nixpkgs> -A xlibs.libXcomposite.out` works here, maybe you are not using the same channel as you build the index for?
