### ISSUE TITLE
error: fetching the file listing for store path [...]

### ISSUE THREAD

**Issue by bjornfor** [bennofs/nix-index#25]
Hi!

I'm trying out nix-index and hit this error:

```
$ ./result/bin/nix-index 
+ querying available packages
error: fetching the file listing for store path '/nix/store/zx9dmnk9lzrimha1xfl1p82wsgpihfs8-udunits-2.2.26' failed
caused by: response to GET 'http://cache.nixos.org/zx9dmnk9lzrimha1xfl1p82wsgpihfs8.ls' failed to parse (response saved to /tmp/file_listing.json)
caused by: expected value at line 1 column 1
 ```

The /tmp/file_listing.json contains some binary data.

The same error happens with nix-index on nixpkgs master and release-18.03 branches.

**Comment by bennofs** [comment]
This appears to be the same issue as #24. It is fixed upstream but there are still some paths that have been built before the fix. Maybe I should put in a workaround (although given enough time, the problem should eventually go away as newly built store paths should not have the problem).

**Comment by bjornfor** [comment]
Glad to hear the problem is fixed. I'm in no hurry, I can wait for store paths to be rebuilt.

Wait... the program _terminates_ due to this error. Perhaps it'd be a good idea to let the program keep going, but indicate with a warning that the index may be incomplete? I'm afraid there are a few long-lived store paths (bootstrap binaries?), so this may keep nix-index from working for a while.

**Comment by bennofs** [comment]
That's actually a very good point, we should definitely concert that into a warning.

**Comment by lheckemann** [comment]
I would highly appreciate if this could be made into a warning as well!

**Comment by 573** [comment]
With 18.09 channel I am still getting this error.

**Comment by bennofs** [comment]
Does it stop building an index though, or do you just get this error? Also, what version of nix-index are you running?

**Comment by lheckemann** [comment]
@bennofs most people still have this issue because there's no release in which it's fixed, i.e. ` nix run nixpkgs.nix-index -c nix-index` is still broken. Would it be possible to make a new release so that we can update the nix-index in nixpkgs to a non-broken version?

**Comment by lheckemann** [comment]
Ah, but it's not backported to 18.09. I'll do that :)

**Comment by lheckemann** [comment]
Actually, I'm a bit confused…

```
[linus@lugn:~]$ nix build -f channel:nixos-18.09 nix-index

[linus@lugn:~]$ ./result/bin/nix-index --version
Nixpkgs Files Indexer 0.1.0

[linus@lugn:~]$ nix eval -f channel:nixos-18.09 nix-index.name
"nix-index-0.1.1"

```

**Comment by bennofs** [comment]
oh, it might be that I forgot to update the version field for the `0.1.1` release. It should be correct for `0.1.2`.
