### ISSUE TITLE
Tag 0.1.2 release

### ISSUE THREAD

**Issue by cocreature** [bennofs/nix-index#54]
Thanks for nix-index! I just noticed that the 0.1.2 which according to the changelog was released on 2018-09-18 doesn’t have a git tag. It would be great if you could add and push such a tag to make it easy to reference and so that it shows up in the releases tab.

**Comment by bennofs** [comment]
Thanks for notifying me about this, I forgot to `git push --tags`

**Comment by cocreature** [comment]
Thanks!
